from flask import Flask, render_template, request, jsonify
from models import mysql_db
from ClockIn import ClockIn
app = Flask(__name__)


@app.route("/in", methods=['GET', 'POST'])
def clock_that_bitch_in():
    clock = ClockIn()
    return clock.punch_in()


@app.route("/out", methods=['GET', 'POST'])
def clock_that_bitch_out():
    clock = ClockIn()
    return clock.punch_out()


@app.route("/")
def main():
    return render_template('base.html')


@app.route("/list_entries")
def list_entries():
    clock = ClockIn()
    return clock.list_entries_for_day()


@app.route("/total_time_today")
def total_time_today():
    clock = ClockIn()
    return clock.total_time_today()


@app.route("/total_time_this_week")
def total_time_this_week():
    clock = ClockIn()
    return clock.total_time_this_week()


# This hook ensures that a connection is opened to handle any queries
# generated by the request.
@app.before_request
def _db_connect():
    mysql_db.connect()


# This hook ensures that the connection is closed when we've finished
# processing the request.
@app.teardown_request
def _db_close(exc):
    if not mysql_db.is_closed():
        mysql_db.close()


if __name__ == "__main__":
    # app.run(debug=True)
    pass
